;;
; Copyright Jacques Deschênes 2019 
; This file is part of MONA 
;
;     MONA is free software: you can redistribute it and/or modify
;     it under the terms of the GNU General Public License as published by
;     the Free Software Foundation, either version 3 of the License, or
;     (at your option) any later version.
;
;     MONA is distributed in the hope that it will be useful,
;     but WITHOUT ANY WARRANTY; without even the implied warranty of
;     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;     GNU General Public License for more details.
;
;     You should have received a copy of the GNU General Public License
;     along with MONA.  If not, see <http://www.gnu.org/licenses/>.
;;

;-------------------------------------------------------
;     ASCII control  values
;     CTRL_x   are VT100 keyboard values  
;-------------------------------------------------------
		CTRL_A = 1
		CTRL_B = 2
		CTRL_C = 3
		CTRL_D = 4
		CTRL_E = 5
		CTRL_F = 6

        BELL = 7    ; vt100 terminal generate a sound.
		CTRL_G = 7

		BSP = 8     ; back space 
		CTRL_H = 8  

    	TAB = 9     ; horizontal tabulation
        CTRL_I = 9

		NL = 10     ; new line 
        CTRL_J = 10 

        VT = 11     ; vertical tabulation 
		CTRL_K = 11

        FF = 12      ; new page
		CTRL_L = 12

		CR = 13      ; carriage return 
		CTRL_M = 13

		CTRL_N = 14
		CTRL_O = 15
		CTRL_P = 16
		CTRL_Q = 17
		CTRL_R = 18
		CTRL_S = 19
		CTRL_T = 20
		CTRL_U = 21
		CTRL_V = 22
		CTRL_W = 23
		CTRL_X = 24
		CTRL_Y = 25
		CTRL_Z = 26
		ESC = 27
		SPACE = 32
		COMMA = 44 
		SHARP = 35
		TICK = 39